language: node_js
node_js:
- 4.4.4
before_script:
- openssl aes-256-cbc -K $encrypted_d81f9e581824_key -iv $encrypted_d81f9e581824_iv
  -in deploy_key.enc -out deploy_key -d
- chmod +x ./scripts/deploy.sh
script: gulp build
after_success: npm run-script deploy